project:
  type: book

toc: true
number-sections: true
top-level-division: chapter

book:
  title: "Evaluating Quarto with Julia and Unicode"
  author: "Gregory Vernon"
  date: "9/17/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

execute:
  timeout: -1 # No timeout for the entire document

format:
  html:
    theme: cosmo
  pdf:
    pdf-engine: xelatex
    latex-auto-install: true
    latex-clean: true
    latex-tinytex: false
    keep-tex: true
    mainfont: "Times New Roman"
    monofont: "JuliaMono"
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{amsmath}
        \usepackage{amssymb}
        \usepackage{mathpazo}
        \usepackage{mathtools}
        \usepackage{bm}
        %\usepackage{breqn}
        %\newcommand{\Real}{\mathbb{R}}
        %\newcommand{\Inner}[2]{\left\langle #1, #2 \right\rangle}
        %\newcommand{\Vector}[1]{\mathbf{\mathit{#1}}}
        %\newcommand{\Matrix}[1]{\boldsymbol{\mathrm{#1}}}
        %\newcommand{\ChangeBasisOp}[2]{\Matrix{R}_{\tiny{\Matrix{#1} \rightarrow \Matrix{#2}}}}